<?php
namespace App\Services;
use App\Product;
use App\Order;
use App\Address;
use App\StoreRecord;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
class Commerce {
 public static function money($value){return '₹'.number_format($value/100,2);}
 public static function owner(){if(!session()->has('store_owner'))session(['store_owner'=>(string)Str::uuid()]);return session('store_owner');}
 public static function settings(){return optional(StoreRecord::in('settings')->where('name','store')->first())->data?:['name'=>'NovaCart','tax'=>5,'free_threshold'=>2999];}
 public static function owned($q){return Auth::check()?$q->where('user_id',Auth::id()):$q->whereNull('user_id')->where('session_key',self::owner());}
 public static function cart(){return DB::table('carts')->where('session_key',Auth::check()?'user:'.Auth::id():self::owner())->first();}
 public static function cartId(){if($c=self::cart())return $c->id;return DB::table('carts')->insertGetId(['user_id'=>Auth::id(),'session_key'=>Auth::check()?'user:'.Auth::id():self::owner(),'created_at'=>now(),'updated_at'=>now()]);}
 public static function items(){if(!$c=self::cart())return collect();return DB::table('cart_items')->where('cart_id',$c->id)->get()->map(function($i){$i->product=Product::find($i->product_id);return $i;});}
 public static function add(Product $p,$quantity,$variant){CustomerProfile::requireComplete();if(!$p->active||$p->trashed())self::error('This product is unavailable.');if(!in_array($variant,$p->options,true))self::error('Choose a valid variant.');$cart=self::cartId();$row=DB::table('cart_items')->where(['cart_id'=>$cart,'product_id'=>$p->id,'variant'=>$variant])->first();$total=($row?$row->quantity:0)+$quantity;if($total<1||$total>$p->stock)self::error('The requested quantity exceeds available stock.');DB::table('cart_items')->updateOrInsert(['cart_id'=>$cart,'product_id'=>$p->id,'variant'=>$variant],['quantity'=>$total,'created_at'=>now(),'updated_at'=>now()]);}
 public static function error($message){throw ValidationException::withMessages(['store'=>$message]);}
 public static function totals($items,$shippingId,$couponCode=null,$lock=false){$subtotal=0;foreach($items as $item){if(!$item->product||!$item->product->active)self::error('A product in your cart is unavailable.');$subtotal+=$item->product->price*$item->quantity;}$settings=self::settings();$shipping=StoreRecord::in('shipping_methods')->where('active',true)->find($shippingId);if(!$shipping)self::error('Choose an available delivery method.');$coupon=null;$discount=0;if($couponCode){$query=StoreRecord::in('coupons')->where('name',strtoupper(trim($couponCode)))->where('active',true);$coupon=$lock?$query->lockForUpdate()->first():$query->first();if(!$coupon)self::error('Coupon unavailable.');$c=$coupon->data;$used=DB::table('coupon_usages')->where('coupon_id',$coupon->id)->count();if((!empty($c['starts'])&&$c['starts']>date('Y-m-d'))||(!empty($c['expires'])&&$c['expires']<date('Y-m-d'))||$subtotal<(float)($c['minimum']??0)*100||(!empty($c['limit'])&&$used>=$c['limit'])||(!empty($c['email'])&&$c['email']!==optional(Auth::user())->email))self::error('Coupon expired, usage limit reached, or minimum order not met.');$discount=$c['type']==='fixed'?(int)round($c['value']*100):(int)round($subtotal*$c['value']/100);$discount=min($discount,$subtotal,empty($c['maximum'])?PHP_INT_MAX:(int)round($c['maximum']*100));}$ship=$shipping->data;$charge=!empty($ship['free_threshold'])&&$subtotal>=$ship['free_threshold']*100?0:(int)round(($ship['charge']??0)*100);$tax=(int)round(($subtotal-$discount)*($settings['tax']??0)/100);return ['subtotal'=>$subtotal,'discount'=>$discount,'shipping'=>$charge,'tax'=>$tax,'total'=>$subtotal-$discount+$charge+$tax,'coupon'=>$coupon,'method'=>$shipping];}
 public static function checkout($input){CustomerProfile::requireComplete();return DB::transaction(function()use($input){$existing=Order::where('idempotency_key',$input['key'])->first();if($existing){if(!self::owned(Order::where('id',$existing->id))->exists())abort(403);return $existing;}$cart=self::cart();if(!$cart)self::error('Your cart is empty.');$items=DB::table('cart_items')->where('cart_id',$cart->id)->orderBy('product_id')->get();if(!$items->count())self::error('Your cart is empty.');foreach($items as $i){$i->product=Product::where('id',$i->product_id)->lockForUpdate()->first();if(!$i->product||$i->quantity>$i->product->stock)self::error('A product has insufficient stock.');} $a=self::owned(Address::query())->find($input['address_id']);if(!$a)self::error('Choose your shipping address.');$t=self::totals($items,$input['shipping_id'],$input['coupon']??null,true);$settings=self::settings();$methods=array_map('trim',explode(',',$settings['payment_methods']??'Test card / UPI,Cash on delivery (test)'));if(!in_array($input['payment'],$methods,true))self::error('Choose an available payment method.');$o=Order::create(['number'=>'NC-'.strtoupper(Str::random(10)),'idempotency_key'=>$input['key'],'user_id'=>Auth::id(),'session_key'=>self::owner(),'email'=>$input['email'],'status'=>'Placed','subtotal'=>$t['subtotal'],'discount'=>$t['discount'],'shipping'=>$t['shipping'],'tax'=>$t['tax'],'total'=>$t['total'],'coupon_id'=>$t['coupon']?$t['coupon']->id:null,'shipping_method_id'=>$t['method']->id,'payment_method'=>$input['payment'],'timeline'=>[['status'=>'Placed','date'=>now()->toIso8601String()]]]);foreach($items as $i){if(!DB::table('products')->where('id',$i->product_id)->where('stock','>=',$i->quantity)->decrement('stock',$i->quantity))self::error('Stock changed. Please try again.');$o->items()->create(['product_id'=>$i->product_id,'name'=>$i->product->name,'sku'=>$i->product->sku,'image'=>$i->product->image,'variant'=>$i->variant,'quantity'=>$i->quantity,'price'=>$i->product->price]);DB::table('inventory')->insert(['product_id'=>$i->product_id,'adjustment'=>-$i->quantity,'reason'=>$o->number,'user_id'=>Auth::id(),'created_at'=>now(),'updated_at'=>now()]);}DB::table('order_addresses')->insert(['order_id'=>$o->id,'data'=>json_encode($a->toArray())]);DB::table('payments')->insert(['order_id'=>$o->id,'method'=>$input['payment'],'amount'=>$o->total,'status'=>'Test — no payment collected','created_at'=>now(),'updated_at'=>now()]);DB::table('shipments')->insert(['order_id'=>$o->id,'method'=>$t['method']->name,'status'=>'Pending','created_at'=>now(),'updated_at'=>now()]);if($t['coupon'])DB::table('coupon_usages')->insert(['coupon_id'=>$t['coupon']->id,'order_id'=>$o->id,'user_id'=>Auth::id(),'session_key'=>self::owner(),'created_at'=>now(),'updated_at'=>now()]);DB::table('cart_items')->where('cart_id',$cart->id)->delete();self::notify($o,'Order '.$o->number.' placed');self::log('Order placed',['number'=>$o->number]);return $o;},3);}
 public static function status(Order $order,$status,$admin=false){DB::transaction(function()use($order,$status,$admin){$o=Order::where('id',$order->id)->lockForUpdate()->first();$allowed=$admin?['Confirmed','Shipped','Delivered','Cancelled','Refunded']:['Cancelled','Return requested'];if(!in_array($status,$allowed,true)||in_array($o->status,['Cancelled','Refunded'],true))self::error('This status change is unavailable.');if(!$admin&&$status==='Cancelled'&&!in_array($o->status,['Placed','Confirmed'],true))self::error('The order can no longer be cancelled.');if(!$admin&&$status==='Return requested'){if($o->status!=='Delivered')self::error('Returns are available after delivery.');$delivered=collect($o->timeline)->last(function($t){return $t['status']==='Delivered';});if(!$delivered||strtotime($delivered['date'])<time()-7*86400)self::error('The 7-day return window has closed.');}if(in_array($status,['Cancelled','Refunded'],true)&&!$o->stock_restored){foreach($o->items as $item){DB::table('products')->where('id',$item->product_id)->increment('stock',$item->quantity);DB::table('inventory')->insert(['product_id'=>$item->product_id,'adjustment'=>$item->quantity,'reason'=>$status.' '.$o->number,'user_id'=>Auth::id(),'created_at'=>now(),'updated_at'=>now()]);}$o->stock_restored=true;}$timeline=$o->timeline;$timeline[]=['status'=>$status,'date'=>now()->toIso8601String()];$o->update(['status'=>$status,'timeline'=>$timeline,'stock_restored'=>$o->stock_restored]);DB::table('shipments')->where('order_id',$o->id)->update(['status'=>$status,'updated_at'=>now()]);if($status==='Refunded')DB::table('payments')->where('order_id',$o->id)->update(['status'=>'Test refund recorded — no money moved','updated_at'=>now()]);self::notify($o,'Order '.$o->number.': '.$status);self::log('Order status changed',['number'=>$o->number,'status'=>$status]);});}
 public static function notify(Order $o,$name){StoreRecord::in('notifications')->create(['user_id'=>$o->user_id,'session_key'=>$o->session_key,'name'=>$name,'data'=>['order_id'=>$o->id]]);}
 public static function log($name,$data=[]){StoreRecord::in('activity_logs')->create(['name'=>$name,'user_id'=>Auth::id(),'session_key'=>self::owner(),'data'=>$data]);}
 public static function mergeGuestCart(){ $guest=DB::table('carts')->where('session_key',self::owner())->first();foreach($guest?DB::table('cart_items')->where('cart_id',$guest->id)->get():[] as $i){$p=Product::find($i->product_id);if($p&&$p->active){try{self::add($p,$i->quantity,$i->variant);DB::table('cart_items')->where('id',$i->id)->delete();}catch(ValidationException $e){session()->flash('notice','Some guest items could not be merged because stock changed.');}}}DB::table('orders')->whereNull('user_id')->where('session_key',self::owner())->update(['user_id'=>Auth::id()]);DB::table('addresses')->whereNull('user_id')->where('session_key',self::owner())->update(['user_id'=>Auth::id()]);DB::table('notifications')->whereNull('user_id')->where('session_key',self::owner())->update(['user_id'=>Auth::id()]);}
}
