@php($profileAddress=isset($profileUser)?\App\Services\CustomerProfile::address($profileUser):null)
<div class="form-grid">
 <label>Full name <span aria-hidden="true">*</span><input name="name" required minlength="2" maxlength="100" autocomplete="name" value="{{ old('name',isset($profileUser)?$profileUser->name:'') }}">@error('name')<small class="danger">{{ $message }}</small>@enderror</label>
 <label>Email <span aria-hidden="true">*</span><input type="email" name="email" required maxlength="190" autocomplete="email" value="{{ old('email',isset($profileUser)?$profileUser->email:'') }}">@error('email')<small class="danger">{{ $message }}</small>@enderror</label>
 <label>Mobile number <span aria-hidden="true">*</span><input type="tel" name="phone" required maxlength="14" pattern="(?:\+91[ \-]?)?[6-9][0-9]{9}" title="Enter a 10-digit mobile number starting with 6, 7, 8 or 9. +91 is optional." autocomplete="tel" placeholder="9876543210" value="{{ old('phone',isset($profileUser)?$profileUser->phone:'') }}"><small>10-digit Indian mobile number; +91 is optional. Use a number not registered to another account.</small>@error('phone')<small class="danger">{{ $message }}</small>@enderror</label>
 <label>Address type <span aria-hidden="true">*</span><select name="type" required>@foreach(['Home','Office','Other'] as $type)<option value="{{ $type }}" {{ old('type',optional($profileAddress)->type??'Home')===$type?'selected':'' }}>{{ $type }}</option>@endforeach</select></label>
 <label class="span2">Full address <span aria-hidden="true">*</span><textarea name="address" required minlength="5" maxlength="255" autocomplete="street-address" placeholder="House / flat number, building, street and locality">{{ old('address',optional($profileAddress)->address) }}</textarea>@error('address')<small class="danger">{{ $message }}</small>@enderror</label>
 <label>City <span aria-hidden="true">*</span><input name="city" required minlength="2" maxlength="100" autocomplete="address-level2" value="{{ old('city',optional($profileAddress)->city) }}">@error('city')<small class="danger">{{ $message }}</small>@enderror</label>
 <label>State <span aria-hidden="true">*</span><input name="state" required minlength="2" maxlength="100" autocomplete="address-level1" value="{{ old('state',optional($profileAddress)->state) }}">@error('state')<small class="danger">{{ $message }}</small>@enderror</label>
 <label>PIN code <span aria-hidden="true">*</span><input name="pincode" required pattern="[1-9][0-9]{5}" maxlength="6" inputmode="numeric" autocomplete="postal-code" value="{{ old('pincode',optional($profileAddress)->pincode) }}">@error('pincode')<small class="danger">{{ $message }}</small>@enderror</label>
 <label>Country<input value="India" readonly autocomplete="country-name"><small>This store currently delivers within India.</small></label>
</div>
