<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RealWorldProductsSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'sku' => 'NC-RIC-001',
                'name' => 'India Gate Basmati Rice 1 kg',
                'price' => 24400,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'India Gate Basmati Rice 1 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-RIC-002',
                'name' => 'Daawat Rozana Super Basmati Rice 5 kg',
                'price' => 48900,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Daawat Rozana Super Basmati Rice 5 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-ATT-003',
                'name' => 'Aashirvaad Shudh Chakki Atta 5 kg',
                'price' => 24400,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Aashirvaad Shudh Chakki Atta 5 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-DAL-004',
                'name' => 'Tata Sampann Toor Dal 1 kg',
                'price' => 20900,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Tata Sampann Toor Dal 1 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-DAL-005',
                'name' => 'Tata Sampann Moong Dal 1 kg',
                'price' => 15900,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Tata Sampann Moong Dal 1 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-DAL-006',
                'name' => 'Rajdhani Chana Dal 1 kg',
                'price' => 11400,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Rajdhani Chana Dal 1 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-OIL-007',
                'name' => 'Fortune Sunflower Oil 1 L',
                'price' => 17000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Fortune Sunflower Oil 1 L',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-OIL-008',
                'name' => 'Saffola Gold Edible Oil 1 L',
                'price' => 19000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Saffola Gold Edible Oil 1 L',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-SUG-009',
                'name' => 'Tata Sugar 1 kg',
                'price' => 5200,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Tata Sugar 1 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-SLT-010',
                'name' => 'Tata Iodised Salt 1 kg',
                'price' => 2800,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Tata Iodised Salt 1 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-TEA-011',
                'name' => 'Tata Tea Premium 500 g',
                'price' => 27500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Tata Tea Premium 500 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-COF-012',
                'name' => 'Nescafe Classic Coffee 100 g',
                'price' => 32500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Nescafe Classic Coffee 100 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-NOD-013',
                'name' => 'Maggi 2-Minute Masala Noodles 560 g',
                'price' => 11000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Maggi 2-Minute Masala Noodles 560 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-PAS-014',
                'name' => 'Bambino Macaroni 500 g',
                'price' => 7500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Bambino Macaroni 500 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-BIS-015',
                'name' => 'Parle-G Original Biscuits 800 g',
                'price' => 7500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Parle-G Original Biscuits 800 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-BIS-016',
                'name' => 'Britannia Good Day Cashew 600 g',
                'price' => 13500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Britannia Good Day Cashew 600 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-BIS-017',
                'name' => 'Oreo Original Vanilla Creme 120 g',
                'price' => 3500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Oreo Original Vanilla Creme 120 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-SNK-018',
                'name' => 'Haldiram\'s Aloo Bhujia 200 g',
                'price' => 5500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Haldiram\'s Aloo Bhujia 200 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-SNK-019',
                'name' => 'Lay\'s Classic Salted Potato Chips 50 g',
                'price' => 2000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Lay\'s Classic Salted Potato Chips 50 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-SPC-020',
                'name' => 'Everest Turmeric Powder 200 g',
                'price' => 5500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Everest Turmeric Powder 200 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-SPC-021',
                'name' => 'MDH Garam Masala 100 g',
                'price' => 6500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'MDH Garam Masala 100 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-SPC-022',
                'name' => 'Tata Sampann Red Chilli Powder 200 g',
                'price' => 8400,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Tata Sampann Red Chilli Powder 200 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-SAU-023',
                'name' => 'Kissan Fresh Tomato Ketchup 500 g',
                'price' => 12500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Kissan Fresh Tomato Ketchup 500 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-SAU-024',
                'name' => 'Kissan Mixed Fruit Jam 200 g',
                'price' => 8500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Kissan Mixed Fruit Jam 200 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-DRK-025',
                'name' => 'Coca-Cola Soft Drink 750 ml',
                'price' => 4500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Coca-Cola Soft Drink 750 ml',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-DRK-026',
                'name' => 'Thums Up Soft Drink 750 ml',
                'price' => 4500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Thums Up Soft Drink 750 ml',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-DRK-027',
                'name' => 'Real Fruit Power Mixed Fruit 1 L',
                'price' => 12500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Real Fruit Power Mixed Fruit 1 L',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-DAI-028',
                'name' => 'Amul Butter 100 g',
                'price' => 6200,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Amul Butter 100 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-DAI-029',
                'name' => 'Amul Taaza Milk 1 L',
                'price' => 6200,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Amul Taaza Milk 1 L',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-DAI-030',
                'name' => 'Amul Cheese Slices 200 g',
                'price' => 14500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Amul Cheese Slices 200 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-BRF-031',
                'name' => 'Kellogg\'s Corn Flakes 300 g',
                'price' => 18500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Kellogg\'s Corn Flakes 300 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-BRF-032',
                'name' => 'Saffola Oats 1 kg',
                'price' => 17500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Saffola Oats 1 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-CHO-033',
                'name' => 'Cadbury Dairy Milk Chocolate 110 g',
                'price' => 12000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Cadbury Dairy Milk Chocolate 110 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-CHO-034',
                'name' => 'KitKat 4 Finger Chocolate 41.5 g',
                'price' => 3000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'KitKat 4 Finger Chocolate 41.5 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-HOM-035',
                'name' => 'Surf Excel Matic Liquid Detergent 2 L',
                'price' => 39100,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Surf Excel Matic Liquid Detergent 2 L',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-HOM-036',
                'name' => 'Rin Matic Liquid Detergent 2 kg',
                'price' => 21500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Rin Matic Liquid Detergent 2 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-HOM-037',
                'name' => 'Vim Dishwash Liquid 500 ml',
                'price' => 11000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Vim Dishwash Liquid 500 ml',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-HOM-038',
                'name' => 'Harpic Bathroom Cleaner 1 L',
                'price' => 19800,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Harpic Bathroom Cleaner 1 L',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-HOM-039',
                'name' => 'Lizol Floor Cleaner 1 L',
                'price' => 20500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Lizol Floor Cleaner 1 L',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-PC-040',
                'name' => 'Dettol Original Handwash 250 ml',
                'price' => 9500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Dettol Original Handwash 250 ml',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-PC-041',
                'name' => 'Colgate Strong Teeth Toothpaste 200 g',
                'price' => 11000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Colgate Strong Teeth Toothpaste 200 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-PC-042',
                'name' => 'Dove Cream Beauty Bathing Bar 100 g',
                'price' => 6500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Dove Cream Beauty Bathing Bar 100 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-PC-043',
                'name' => 'Clinic Plus Strong & Long Shampoo 340 ml',
                'price' => 19000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Clinic Plus Strong & Long Shampoo 340 ml',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-PC-044',
                'name' => 'Lux Soft Touch Soap 100 g',
                'price' => 4000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Lux Soft Touch Soap 100 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-KIT-045',
                'name' => 'Tata Sampann Poha 500 g',
                'price' => 7500,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Tata Sampann Poha 500 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-KIT-046',
                'name' => 'Rajdhani Besan 1 kg',
                'price' => 11400,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Rajdhani Besan 1 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-KIT-047',
                'name' => 'Amul Pure Ghee 1 L',
                'price' => 65000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Amul Pure Ghee 1 L',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-KIT-048',
                'name' => 'India Gate Jeera Rice 1 kg',
                'price' => 21900,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'India Gate Jeera Rice 1 kg',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-KIT-049',
                'name' => 'Britannia Marie Gold Biscuits 250 g',
                'price' => 3000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Britannia Marie Gold Biscuits 250 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
            [
                'sku' => 'NC-KIT-050',
                'name' => 'Nescafe Sunrise Coffee 100 g',
                'price' => 24000,
                'old_price' => 0,
                'stock' => 0,
                'image' => null,
                'description' => 'Nescafe Sunrise Coffee 100 g',
                'specifications' => null,
                'variants' => null,
                'featured' => false,
                'active' => true,
            ],
        ];

        foreach ($products as $product) {
            // Existing stock and prices belong to the receipt ledger and admin.
            if(DB::table('products')->where('sku',$product['sku'])->exists())continue;
            DB::table('products')->updateOrInsert(
                ['sku' => $product['sku']],
                array_merge($product, [
                    'updated_at' => now(),
                    'created_at' => now(),
                ])
            );
        }

        $this->command->info('Real-world NovaCart products seeded successfully.');
    }
}