@extends('layouts.admin')
@section('admin_title','Receive stock')
@section('admin_content')
<link rel="stylesheet" href="/outward.css"><div class="ow"><div class="ow-head"><div><a href="{{ route('admin.inward') }}">← Inward receipts</a><h1>Receive stock</h1><p>Record supplier invoices and batches. Purchase costs stay separate from the selling price.</p></div><a class="ow-btn" href="{{ route('admin.inward.import') }}">Bulk import</a></div>@include('admin.outward.errors')
<form method="post" action="{{ route('admin.inward.store') }}">@csrf<div class="ow-card ow-grid">
@foreach(['number'=>'Inward number','supplier'=>'Supplier name','supplier_invoice_no'=>'Supplier invoice / bill number','warehouse'=>'Warehouse / store','received_by'=>'Received by'] as $field=>$label)<div><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$field==='number'?'IN-'.strtoupper(\Illuminate\Support\Str::random(10)):($field==='received_by'?auth()->user()->name:($field==='warehouse'?'Main inventory':''))) }}" required maxlength="{{ $field==='number'?80:($field==='supplier_invoice_no'?120:190) }}"></div>@endforeach
<div><label for="inward_date">Received date</label><input id="inward_date" type="date" name="inward_date" value="{{ old('inward_date',today()->toDateString()) }}" max="{{ today()->toDateString() }}" required></div><div><label for="invoice_date">Invoice date</label><input id="invoice_date" type="date" name="invoice_date" value="{{ old('invoice_date',today()->toDateString()) }}" max="{{ today()->toDateString() }}" required></div></div>
<div id="receipt-lines">@foreach(old('items',[['quantity'=>1,'gst_percent'=>0]]) as $index=>$line)<div class="ow-card receipt-line"><h3>Product batch</h3><div class="ow-grid"><div><label>Product<select name="items[{{ $index }}][product_id]" required><option value="">Choose product</option>@foreach($products as $p)<option value="{{ $p->id }}" {{ (string)($line['product_id']??'')===(string)$p->id?'selected':'' }}>{{ $p->name }} · {{ $p->sku }}</option>@endforeach</select></label></div><div><label>Batch number<input name="items[{{ $index }}][batch_number]" value="{{ $line['batch_number']??'' }}" required maxlength="80"></label></div><div><label>Received quantity<input type="number" name="items[{{ $index }}][quantity]" value="{{ $line['quantity']??1 }}" required min="1" max="1000000"></label></div><div><label>Purchase cost per unit (₹)<input type="number" step="0.01" name="items[{{ $index }}][unit_cost]" value="{{ $line['unit_cost']??'' }}" required min="0" max="10000000"></label></div><div><label>GST (%)<input type="number" step="0.01" name="items[{{ $index }}][gst_percent]" value="{{ $line['gst_percent']??0 }}" min="0" max="100" required></label></div><div><label>Manufacturing date<input type="date" name="items[{{ $index }}][manufactured_on]" value="{{ $line['manufactured_on']??'' }}" max="{{ today()->toDateString() }}"></label></div><div><label>Expiry date<input type="date" name="items[{{ $index }}][expires_on]" value="{{ $line['expires_on']??'' }}"></label></div></div><button type="button" class="ow-btn remove-line">Remove batch</button></div>@endforeach</div>
<div class="ow-card"><button id="add-receipt-line" type="button" class="ow-btn">Add another batch</button><label for="notes">Receipt notes</label><textarea id="notes" name="notes" maxlength="1000">{{ old('notes') }}</textarea><p>One line per product batch. Saving a receipt adds stock and leaves selling prices unchanged.</p><button class="ow-btn ow-primary">Save receipt and add stock</button></div></form></div>
@endsection
@section('scripts')<script>document.addEventListener('DOMContentLoaded',function(){var list=document.getElementById('receipt-lines'),next={{ count(old('items',[[]])) }};document.getElementById('add-receipt-line').addEventListener('click',function(){if(list.children.length>=100)return;var row=list.firstElementChild.cloneNode(true);row.querySelectorAll('[name]').forEach(function(input){input.name=input.name.replace(/items\[\d+\]/,'items['+next+']');input.value=input.name.indexOf('[quantity]')>=0?'1':input.name.indexOf('[gst_percent]')>=0?'0':'';});next++;list.appendChild(row);});list.addEventListener('click',function(event){if(event.target.classList.contains('remove-line')&&list.children.length>1)event.target.closest('.receipt-line').remove();});});</script>@endsection
