@extends('layouts.admin')@section('admin_title',($item?'Edit ':'Add ').($module==='products'?'product':strtolower($c['title'])))@section('admin_content')<form class="admin-card panel-form" method="post" enctype="multipart/form-data" action="{{ $item?route('admin.update',[$module,$item->id]):route('admin.store',$module) }}">@csrf @if($item)@method('PUT')@endif<div class="form-grid">@foreach($c['fields'] as $field)@if($module==='users'&&$item&&in_array($field,['password','password_confirmation']))@continue @endif @php($value=old($field,$values[$field]??($field==='product_id'?request('product_id'):'')))<label class="{{ in_array($field,['description','specifications','permissions','about','terms','privacy','returns'])?'span2':'' }}">{{ $module==='coupons'&&$field==='name'?'Coupon code':ucwords(str_replace('_',' ',$field)) }}
@if(in_array($field,['active','featured','approved']))<span class="check-label"><input type="checkbox" name="{{ $field }}" value="1" {{ $value?'checked':'' }}> Enabled</span>
@elseif($field==='permissions')<div class="permission-grid">@foreach(array_merge(['dashboard'],array_keys(config('store.modules'))) as $permission)<label class="check-label"><input type="checkbox" name="permissions[]" value="{{ $permission }}" {{ in_array($permission,is_array($value)?$value:[])?'checked':'' }}> {{ $permission==='dashboard'?'Dashboard':config('store.modules.'.$permission.'.title') }}@error($field)<span class="aw-inline-error" role="alert">{{ $errors->first($field) }}</span>@endif</label>@endforeach</div>
@elseif(in_array($field,['category_id','brand_id','parent_id','role_id','product_id']))@php($table=['category_id'=>'categories','brand_id'=>'brands','parent_id'=>'categories','role_id'=>'roles','product_id'=>'products'][$field])<select name="{{ $field }}" {{ in_array($field,['role_id','product_id'])?'required':'' }}><option value="">Choose {{ str_replace('_id','',$field) }}</option>@foreach($table==='products'?\App\Product::all():\App\StoreRecord::in($table)->get() as $option)<option value="{{ $option->id }}" {{ $value==$option->id?'selected':'' }}>{{ $option->name }}</option>@endforeach</select>
@elseif($field==='delivery_type')<select name="delivery_type">@foreach(['standard'=>'Standard','fresh'=>'Fresh — same-day delivery','dairy'=>'Dairy — within 60 minutes'] as $type=>$label)<option value="{{ $type }}" {{ ($value?:'standard')===$type?'selected':'' }}>{{ $label }}</option>@endforeach</select>
@elseif($field==='delivery_minutes')<input type="number" name="delivery_minutes" min="1" max="240" required value="{{ $value?:60 }}"><small>Preparation and delivery time in minutes. Dairy: maximum 60 minutes.</small>
@elseif($field==='type'&&$module==='coupons')<select name="type"><option value="percentage" {{ $value==='percentage'?'selected':'' }}>Percentage</option><option value="fixed" {{ $value==='fixed'?'selected':'' }}>Fixed amount</option></select>
@elseif(in_array($field,['description','specifications','response','about','terms','privacy','returns']))<textarea name="{{ $field }}">{{ $value }}</textarea>
@else<input name="{{ $field }}" value="{{ is_array($value)?json_encode($value):$value }}" {{ in_array($field,['name','sku','price','stock','value','charge','adjustment','reason'])?'required':'' }} type="{{ in_array($field,['price','old_price','stock','value','minimum','maximum','limit','charge','free_threshold','tax','position','adjustment'])?'number':(in_array($field,['starts','expires'])?'date':(in_array($field,['email','support_email'])?'email':(in_array($field,['password','password_confirmation'])?'password':'text'))) }}" step="{{ in_array($field,['stock','limit','position','adjustment'])?'1':'any' }}">@if(in_array($field,['price','old_price','charge','minimum','maximum','free_threshold']))<small>Enter amount in rupees.</small>@endif @if($field==='gallery')<small>Comma-separated image URLs.</small>@endif @if($field==='variants')<small>Comma-separated options, e.g. Black / M, Black / L.</small>@endif @endif
@if($errors->has($field))<span class="aw-inline-error" role="alert">{{ $errors->first($field) }}</span>@endif</label>@endforeach</div>@if($module==='products')<label class="upload">Upload product image<input type="file" name="image_upload" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG, WebP · Maximum 5 MB</small>@if($values['image']??null)<img src="{{ $values['image'] }}" alt="Product preview">@endif</label>@endif @if($module==='reviews')<p>{{ optional($item->product)->name }} · {{ $item->rating }} stars</p><blockquote>{{ $item->text }}</blockquote>@endif<div class="editor-footer"><a class="outline" href="{{ route('admin.index',$module) }}">Cancel</a><button class="primary">Save changes</button></div></form>@endsection
