<?php
use Illuminate\Support\Facades\Route;
Route::middleware(\App\Http\Middleware\ActiveAccount::class)->group(function(){
 Route::get('/','ShopController@home')->name('home');Route::get('/shop','ShopController@shop')->name('shop');Route::get('/products/{product}','ShopController@product')->name('products.show');
 Route::get('/login','AccountController@loginForm')->name('login');Route::post('/login','AccountController@login')->middleware('throttle:6,1');Route::get('/register','AccountController@registerForm')->name('register');Route::post('/register','AccountController@register')->middleware('throttle:6,1');Route::post('/logout','AccountController@logout')->name('logout');
 Route::get('/password/reset','AccountController@forgotForm')->name('password.request');Route::post('/password/email','AccountController@sendReset')->name('password.email')->middleware('throttle:3,1');Route::get('/password/reset/{token}','AccountController@resetForm')->name('password.reset');Route::post('/password/reset','AccountController@reset')->name('password.update')->middleware('throttle:6,1');
 Route::get('/cart','ShopController@cart')->name('cart');Route::post('/cart/add/{product}','ShopController@add')->name('cart.add');Route::post('/cart/{id}/quantity','ShopController@updateCart')->name('cart.update');Route::delete('/cart/{id}','ShopController@removeCart')->name('cart.remove');Route::post('/cart/clear','ShopController@clearCart')->name('cart.clear');Route::post('/coupon','ShopController@coupon')->name('coupon');
 Route::get('/checkout','ShopController@checkout')->name('checkout');Route::post('/checkout','ShopController@place')->name('checkout.place')->middleware('throttle:20,1');
 Route::get('/addresses/new','ShopController@addressForm')->name('addresses.new');Route::get('/addresses/{id}/edit','ShopController@addressForm')->name('addresses.edit');Route::post('/addresses','ShopController@addressSave')->name('addresses.store');Route::put('/addresses/{id}','ShopController@addressSave')->name('addresses.update');Route::delete('/addresses/{id}','ShopController@addressDelete')->name('addresses.delete');
 Route::get('/orders','ShopController@orders')->name('orders');Route::get('/orders/{order}','ShopController@order')->name('orders.show');Route::post('/orders/{order}/status','ShopController@status')->name('orders.status');Route::post('/orders/{order}/reorder','ShopController@reorder')->name('orders.reorder');
 Route::get('/notifications','ShopController@notifications')->name('notifications');Route::post('/notifications/read','ShopController@readNotifications')->name('notifications.read');Route::get('/help','ShopController@help')->name('help');Route::post('/help','ShopController@contact')->name('contact')->middleware('throttle:10,1');Route::post('/newsletter','ShopController@newsletter')->name('newsletter')->middleware('throttle:10,1');
 Route::middleware('auth')->group(function(){Route::get('/account','ShopController@account')->name('account');Route::post('/account','AccountController@profile')->name('account.update');Route::post('/account/password','AccountController@password')->name('account.password')->middleware('throttle:6,1');Route::get('/wishlist','ShopController@wishlist')->name('wishlist');Route::post('/wishlist/{product}','ShopController@wish')->name('wishlist.toggle');Route::get('/reviews/{product}/new','ShopController@reviewForm')->name('reviews.new');Route::get('/reviews/{product}/{id}/edit','ShopController@reviewForm')->name('reviews.edit');Route::post('/reviews/{product}','ShopController@reviewSave')->name('reviews.store');Route::put('/reviews/{product}/{id}','ShopController@reviewSave')->name('reviews.update');Route::delete('/reviews/{id}','ShopController@reviewDelete')->name('reviews.delete');Route::get('/email/verify',function(){return redirect('/account');})->name('verification.notice');Route::get('/email/verify/{id}/{hash}','AccountController@verify')->middleware('signed')->name('verification.verify');Route::post('/email/resend','AccountController@resend')->middleware('throttle:3,1')->name('verification.resend');});
 Route::prefix('admin')->middleware(['auth',\App\Http\Middleware\AdminAccess::class])->group(function(){Route::get('/','AdminController@dashboard')->name('admin.dashboard');Route::get('/{module}/export','AdminController@export')->name('admin.export');Route::get('/{module}/create','AdminController@edit')->name('admin.create');Route::get('/{module}/{id}/edit','AdminController@edit')->name('admin.edit');Route::post('/{module}','AdminController@save')->name('admin.store');Route::put('/{module}/{id}','AdminController@save')->name('admin.update');Route::delete('/{module}/{id}','AdminController@delete')->name('admin.delete');Route::post('/orders/{order}/status','AdminController@orderStatus')->defaults('module','orders')->name('admin.order.status');Route::get('/{module}','AdminController@index')->name('admin.index');});
});
