<?php
namespace Tests\Feature;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use App\Product;
use App\Order;
use App\User;
use App\Address;
use App\StoreRecord;
use App\Services\BatchStock;
use App\Services\CustomerProfile;
class BatchInventoryTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->seed(\StoreSeeder::class);}
 private function admin(){$this->actingAs(User::where('email','admin@novacart.test')->first());}
 private function product(){return Product::create(['name'=>'Batch test milk','sku'=>'BATCH-MILK','price'=>9000,'stock'=>0,'active'=>1,'variants'=>'Default','category_id'=>Product::first()->category_id]);}
 private function receive($p,$number,$quantity,$age,$cost,$expiry=null){DB::transaction(function()use($p,$number,$quantity,$age,$cost,$expiry){$p->refresh();BatchStock::receive($p,$quantity,['batch_number'=>$number,'received_at'=>today()->subDays($age)->toDateString(),'supplier_invoice_no'=>'BILL-'.$number,'unit_cost'=>$cost,'expires_on'=>$expiry]);});}
 private function order($p,$qty){$u=User::create(['name'=>'Batch buyer','email'=>'batch'.Str::random(8).'@example.test','password'=>Hash::make('BuyerPass123!'),'role_id'=>StoreRecord::in('roles')->where('name','customer')->value('id')]);CustomerProfile::save($u,['name'=>'Batch buyer','email'=>$u->email,'phone'=>'97'.str_pad($u->id,8,'0',STR_PAD_LEFT),'address'=>'12 Test Road','city'=>'Mumbai','state'=>'Maharashtra','pincode'=>'400001']);$this->actingAs($u);$this->post('/cart/add/'.$p->id,['quantity'=>$qty,'variant'=>'Default'])->assertSessionHasNoErrors();$this->post('/checkout',['key'=>(string)Str::uuid(),'address_id'=>Address::where('user_id',$u->id)->first()->id,'shipping_id'=>StoreRecord::in('shipping_methods')->first()->id,'payment'=>'Test card / UPI','email'=>$u->email])->assertSessionHasNoErrors();return Order::latest('id')->firstOrFail();}
 public function test_fifo_uses_receipt_date_not_expiry_or_cost_and_invoice_keeps_selling_price(){
  $p=$this->product();$this->receive($p,'OLDEST',2,5,4000,today()->addDays(20)->toDateString());$this->receive($p,'NEWER',4,1,5000,today()->addDays(3)->toDateString());$o=$this->order($p,3);$alloc=DB::table('batch_allocations')->join('product_batches','product_batches.id','=','batch_allocations.batch_id')->select('batch_allocations.*','batch_number')->orderBy('batch_allocations.id')->get();$this->assertEquals(['OLDEST','NEWER'],$alloc->pluck('batch_number')->all());$this->assertEquals([2,1],$alloc->pluck('quantity')->all());$this->assertEquals([4000,5000],$alloc->pluck('unit_cost')->all());$this->assertEquals(3,$p->fresh()->stock);$this->assertEquals(9000,$o->items->first()->price);$this->assertNotEmpty($o->invoice_number);$p->update(['price'=>12000]);$this->get('/orders/'.$o->id)->assertOk()->assertSee($o->invoice_number);$this->assertEquals(9000,$o->items->first()->fresh()->price);
 }
 public function test_expired_batches_are_not_sold_and_cancellation_restores_exact_batches_once(){
  $p=$this->product();$this->receive($p,'EXPIRED',3,10,3000,today()->subDay()->toDateString());$this->receive($p,'GOOD',4,2,4000,today()->addDays(5)->toDateString());$this->assertEquals(4,BatchStock::available($p->fresh()));$o=$this->order($p,2);$this->assertEquals('GOOD',DB::table('batch_allocations')->join('product_batches','product_batches.id','=','batch_allocations.batch_id')->value('batch_number'));$this->post('/orders/'.$o->id.'/status',['status'=>'Cancelled'])->assertSessionHasNoErrors();$this->assertEquals(7,$p->fresh()->stock);$this->assertEquals(4,DB::table('product_batches')->where('batch_number','GOOD')->value('remaining_quantity'));$this->post('/orders/'.$o->id.'/status',['status'=>'Cancelled'])->assertSessionHasErrors();$this->assertEquals(7,$p->fresh()->stock);
 }
 public function test_partial_returns_inspect_usable_quantity_and_refund_without_double_restock(){
  $p=$this->product();$this->receive($p,'RETURN-BATCH',10,1,4000,today()->addDays(10)->toDateString());$o=$this->order($p,4);$buyer=auth()->user();$this->admin();$this->post('/admin/orders/'.$o->id.'/status',['status'=>'Delivered'])->assertSessionHasNoErrors();$this->actingAs($buyer);$v=['key'=>(string)Str::uuid(),'reason'=>'Two packs were damaged','quantities'=>[$o->items->first()->id=>2]];$this->post('/orders/'.$o->id.'/returns',$v)->assertRedirect()->assertSessionHasNoErrors();$this->post('/orders/'.$o->id.'/returns',$v)->assertRedirect()->assertSessionHasNoErrors();$this->assertEquals(1,DB::table('order_returns')->count());$entry=DB::table('order_returns')->first();$line=DB::table('order_return_items')->first();$this->admin();$this->post('/admin/returns/'.$entry->id.'/action',['action'=>'receive','notes'=>'Inspected returned goods','restock'=>[$line->id=>1]])->assertSessionHasErrors();$this->post('/admin/returns/'.$entry->id.'/action',['action'=>'approve'])->assertSessionHasNoErrors();$receive=['action'=>'receive','notes'=>'One pack usable, one damaged','restock'=>[$line->id=>1]];$this->post('/admin/returns/'.$entry->id.'/action',$receive)->assertSessionHasNoErrors();$this->assertEquals(7,$p->fresh()->stock);$this->assertEquals('Partially returned',$o->fresh()->status);$this->post('/admin/returns/'.$entry->id.'/action',$receive)->assertSessionHasErrors();$this->post('/admin/returns/'.$entry->id.'/action',['action'=>'refund'])->assertSessionHasNoErrors();$this->post('/admin/returns/'.$entry->id.'/action',['action'=>'refund'])->assertSessionHasErrors();$this->assertEquals(7,$p->fresh()->stock);$this->get('/admin/returns')->assertOk()->assertSee($entry->number);$this->get('/admin/returns/'.$entry->id)->assertOk();$this->actingAs($buyer);$v['key']=(string)Str::uuid();$v['quantities'][$o->items->first()->id]=3;$this->post('/orders/'.$o->id.'/returns',$v)->assertSessionHasErrors();$this->post('/orders/'.$o->id.'/status',['status'=>'Cancelled'])->assertSessionHasErrors();
 }
 public function test_expired_returns_cannot_be_restocked_but_can_be_recorded_as_loss(){
  $p=$this->product();$this->receive($p,'RETURN-EXPIRED',2,1,4000,today()->addDay()->toDateString());$o=$this->order($p,1);$buyer=auth()->user();$this->admin();$this->post('/admin/orders/'.$o->id.'/status',['status'=>'Delivered']);$this->actingAs($buyer);$this->post('/orders/'.$o->id.'/returns',['key'=>(string)Str::uuid(),'reason'=>'Pack is not usable','quantities'=>[$o->items->first()->id=>1]])->assertRedirect()->assertSessionHasNoErrors();$e=DB::table('order_returns')->first();$line=DB::table('order_return_items')->first();$this->admin();$this->post('/admin/returns/'.$e->id.'/action',['action'=>'approve']);DB::table('product_batches')->where('product_id',$p->id)->update(['expires_on'=>today()->subDay()->toDateString()]);$v=['action'=>'receive','notes'=>'Expired on receipt','restock'=>[$line->id=>1]];$this->post('/admin/returns/'.$e->id.'/action',$v)->assertSessionHasErrors();$this->assertEquals('Approved',DB::table('order_returns')->value('status'));$v['restock'][$line->id]=0;$this->post('/admin/returns/'.$e->id.'/action',$v)->assertSessionHasNoErrors();$this->assertEquals(1,$p->fresh()->stock);
 }
 public function test_manual_receipt_search_validation_and_purchase_cost_currency(){
  $this->admin();$p=$this->product();$v=['number'=>'IN-TEST-001','inward_date'=>today()->toDateString(),'supplier'=>'Test supplier','supplier_invoice_no'=>'SUP-BILL-19','invoice_date'=>today()->toDateString(),'warehouse'=>'Main inventory','received_by'=>'Store Admin','items'=>[['product_id'=>$p->id,'batch_number'=>'MANUAL-001','quantity'=>5,'unit_cost'=>'12.75','gst_percent'=>5,'expires_on'=>today()->addDays(3)->toDateString()]]];$this->get('/admin/inward/create')->assertOk();$this->post('/admin/inward',$v)->assertSessionHasNoErrors();$this->assertEquals(5,$p->fresh()->stock);$this->assertEquals(1275,DB::table('product_batches')->where('product_id',$p->id)->value('unit_cost'));$this->assertEquals(6694,DB::table('inwards')->value('total'));$this->assertEquals(9000,$p->fresh()->price);$this->get('/admin/batches?q=SUP-BILL-19')->assertOk()->assertSee('MANUAL-001');$this->get('/admin/inward?search=Batch%20test%20milk')->assertOk()->assertSee('IN-TEST-001');$this->get('/admin/workspace/search?q=SUP-BILL-19')->assertOk()->assertSee('MANUAL-001');$v['number']='IN-TEST-002';$this->post('/admin/inward',$v)->assertSessionHasErrors();$this->assertEquals(1,DB::table('inwards')->count());$this->assertEquals(5,$p->fresh()->stock);$this->get('/admin/inward/template/batches')->assertOk()->assertHeader('Content-Type','text/csv; charset=UTF-8');
 }
 public function test_return_access_and_unowned_order_are_blocked(){
  $p=$this->product();$this->receive($p,'ACCESS',2,1,4000);$o=$this->order($p,1);$this->get('/admin/batches')->assertForbidden();$this->get('/admin/returns')->assertForbidden();$this->admin();$this->post('/orders/'.$o->id.'/returns',['key'=>(string)Str::uuid(),'reason'=>'Invalid user request','quantities'=>[$o->items->first()->id=>1]])->assertForbidden();
 }
 public function test_legacy_inward_currency_is_converted_once_without_changing_stock(){
  $p=Product::first();$stock=$p->stock;$id=DB::table('inwards')->insertGetId(['number'=>'LEGACY-MONEY','inward_date'=>today()->toDateString(),'inward_type'=>'Purchase','warehouse'=>'Main','supplier'=>'Test supplier','supplier_invoice_no'=>'OLD-1','received_by'=>'Admin','subtotal'=>116,'tax'=>6,'total'=>122,'status'=>'Received']);DB::table('inward_items')->insert(['inward_id'=>$id,'product_id'=>$p->id,'sku'=>$p->sku,'product_name'=>$p->name,'received_qty'=>2,'unit_cost'=>58,'subtotal'=>116,'tax'=>6,'total'=>122]);$migration=new \NormalizeLegacyInwardMoney();$migration->up();$this->assertEquals(12200,DB::table('inwards')->where('id',$id)->value('total'));$this->assertEquals(5800,DB::table('inward_items')->where('inward_id',$id)->value('unit_cost'));$migration->up();$this->assertEquals(12200,DB::table('inwards')->where('id',$id)->value('total'));$this->assertEquals($stock,$p->fresh()->stock);
 }
 public function test_legacy_already_returned_orders_cannot_restore_stock_again(){
  $p=$this->product();$this->receive($p,'LEGACY-CLOSED',2,1,4000);$o=$this->order($p,1);$o->update(['status'=>'Return received','stock_restored'=>true]);$this->post('/orders/'.$o->id.'/returns',['key'=>(string)Str::uuid(),'reason'=>'Duplicate historic return','quantities'=>[$o->items->first()->id=>1]])->assertSessionHasErrors();$this->assertEquals(0,DB::table('order_returns')->count());$this->assertEquals(1,$p->fresh()->stock);
 }
 public function test_opening_batch_metadata_changes_do_not_change_stock_or_selling_prices(){
  $this->admin();$p=Product::first();DB::transaction(function()use($p){BatchStock::opening($p);});$b=DB::table('product_batches')->where('product_id',$p->id)->first();$this->get('/admin/batches/'.$b->id.'/edit')->assertOk();$this->put('/admin/batches/'.$b->id,['batch_number'=>'ACTUAL-OPEN-1','supplier_invoice_no'=>'OLD-BILL-5','unit_cost'=>'25.50','manufactured_on'=>substr($b->received_at,0,10),'expires_on'=>today()->addDays(4)->toDateString(),'notes'=>'Entered actual supplier label'])->assertRedirect('/admin/batches')->assertSessionHasNoErrors();$this->assertEquals($p->stock,$p->fresh()->stock);$this->assertEquals($p->price,$p->fresh()->price);$this->assertEquals(2550,DB::table('product_batches')->where('id',$b->id)->value('unit_cost'));
 }
 public function test_csv_import_creates_batch_and_correct_paise_totals_once(){
  $this->admin();$p=$this->product();$headers=['Inward No.','Inward Date','Inward Type','Warehouse / Store','Supplier','Supplier Contact','Supplier Invoice No.','Invoice Date','Purchase Order No.','Delivery Challan No.','Product SKU','Product Name','Ordered Qty','Received Qty','Unit Cost','GST %','Other Charges','Received By','Notes','Batch No.','Manufacturing Date','Expiry Date'];$row=['IN-CSV-1',today()->toDateString(),'Purchase','Main inventory','Supplier','9876543210','BILL-CSV',today()->toDateString(),'PO-1','DC-1',$p->sku,$p->name,2,2,'12.75',5,0,'Store Admin','','CSV-BATCH','',today()->addDays(5)->toDateString()];$stream=fopen('php://temp','r+');fputcsv($stream,$headers);fputcsv($stream,$row);rewind($stream);$file=\Illuminate\Http\UploadedFile::fake()->createWithContent('batch.csv',stream_get_contents($stream));fclose($stream);$response=$this->post('/admin/inward/import/validate',['file'=>$file])->assertSessionHasNoErrors()->assertOk();$preview=$response->viewData('preview');$this->assertEquals(0,$preview['error_count']);$this->post('/admin/inward/import/confirm',['token'=>$preview['token']])->assertSessionHasNoErrors();$this->assertEquals(2,$p->fresh()->stock);$this->assertEquals(1275,DB::table('product_batches')->where('product_id',$p->id)->value('unit_cost'));$this->assertEquals(2678,DB::table('inwards')->value('total'));$this->post('/admin/inward/import/confirm',['token'=>$preview['token']])->assertSessionHasNoErrors();$this->assertEquals(2,$p->fresh()->stock);
 }
}
