<?php
namespace Tests\Feature;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\User;
use App\Product;
use App\Order;
use App\Outward;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
class OutwardTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->seed(\StoreSeeder::class);$this->actingAs(User::where('email','admin@novacart.test')->first());}
 private function payload($intent='draft'){return ['request_key'=>(string)Str::uuid(),'type'=>'Manual Stock Issue','outward_date'=>today()->toDateString(),'source'=>'Main inventory','reason'=>'Test stock issue','intent'=>$intent,'items'=>[['product_id'=>Product::first()->id,'quantity'=>2]]];}
 private function action($o,$action,$extra=[]){return $this->post('/admin/outward/'.$o->id.'/action',['action'=>$action]+$extra);}
 private function order(){ $p=Product::first();$o=Order::create(['number'=>'TEST-'.Str::random(8),'idempotency_key'=>(string)Str::uuid(),'session_key'=>'test','email'=>'buyer@example.test','status'=>'Placed','subtotal'=>$p->price*2,'total'=>$p->price*2,'shipping_method_id'=>1,'payment_method'=>'test','timeline'=>[]]);$o->items()->create(['product_id'=>$p->id,'name'=>$p->name,'sku'=>$p->sku,'image'=>$p->image,'variant'=>'Default','quantity'=>2,'price'=>$p->price]);DB::table('shipments')->insert(['order_id'=>$o->id,'method'=>'test','status'=>'Pending']);return $o;}
 public function test_draft_confirm_is_once_only_and_validation_is_atomic(){ $p=Product::first();$stock=$p->stock;$v=$this->payload();$this->post('/admin/outward',$v)->assertSessionHasNoErrors();$o=Outward::first();$this->assertEquals($stock,$p->fresh()->stock);$this->post('/admin/outward',$v)->assertSessionHasNoErrors();$this->assertEquals(1,Outward::count());$this->action($o,'confirm')->assertSessionHasNoErrors();$this->assertEquals($stock-2,$p->fresh()->stock);$this->action($o,'confirm')->assertSessionHasErrors();$this->assertEquals($stock-2,$p->fresh()->stock);$v=$this->payload('confirm');$v['items'][0]['quantity']=$stock+1;$this->post('/admin/outward',$v)->assertSessionHasErrors();$this->assertEquals(1,Outward::count());}
 public function test_order_dispatch_connects_shipping_without_deducting_stock_twice(){ $order=$this->order();$p=Product::first();$stock=$p->stock;$v=$this->payload('confirm');$v['type']='Order Dispatch';$v['order_id']=$order->id;$this->post('/admin/outward',$v)->assertSessionHasNoErrors();$o=Outward::first();$this->assertEquals($stock,$p->fresh()->stock);$this->action($o,'dispatch')->assertSessionHasErrors();$this->action($o,'pack')->assertSessionHasNoErrors();$this->post('/admin/outward/'.$o->id.'/dispatch-details',['partner'=>'Test carrier','tracking_number'=>'TRACK-123'])->assertSessionHasNoErrors();$this->action($o,'dispatch')->assertSessionHasNoErrors();$this->assertEquals('Shipped',$order->fresh()->status);$this->assertEquals('TRACK-123',DB::table('shipments')->where('order_id',$order->id)->value('tracking_number'));$this->assertEquals($stock,$p->fresh()->stock);$this->action($o,'cancel')->assertSessionHasErrors();$this->action($o,'deliver')->assertSessionHasNoErrors();$this->assertEquals('Delivered',$order->fresh()->status);$this->get('/admin/outward/'.$o->id)->assertOk();$this->get('/admin/outward/'.$o->id.'/print')->assertOk();$this->action($o,'return',['return_condition'=>'restock','return_reason'=>'Inspected and received'])->assertSessionHasNoErrors();$this->assertEquals($stock+2,$p->fresh()->stock);$this->action($o,'return',['return_condition'=>'restock','return_reason'=>'Again'])->assertSessionHasErrors();$this->assertEquals($stock+2,$p->fresh()->stock);}
 public function test_duplicate_orders_cancel_recreate_filters_and_pages(){ $order=$this->order();$v=$this->payload();$v['type']='Order Dispatch';$v['order_id']=$order->id;$this->post('/admin/outward',$v)->assertSessionHasNoErrors();$o=Outward::first();$v['request_key']=(string)Str::uuid();$this->post('/admin/outward',$v)->assertSessionHasErrors();$this->action($o,'cancel')->assertSessionHasNoErrors();$this->post('/admin/outward',$v)->assertSessionHasNoErrors();$this->get('/admin/outward?q='.$order->number)->assertOk()->assertSee($order->number);$this->get('/admin/outward/create')->assertOk();$this->get('/admin/outward/'.Outward::latest('id')->first()->id.'/edit')->assertOk();$this->get('/admin/outward/export')->assertOk();}
 public function test_access_and_transfer_loss_validation(){ $this->actingAs(User::create(['name'=>'Buyer','email'=>'buyer2@example.test','password'=>'hash']));$this->get('/admin/outward')->assertForbidden();$this->get('/admin/outward/create')->assertForbidden();$this->post('/admin/outward',$this->payload())->assertForbidden();$this->actingAs(User::where('email','admin@novacart.test')->first());$p=Product::first();$stock=$p->stock;$v=$this->payload('confirm');$v['type']='Internal Transfer';$v['destination']='Second location';$this->post('/admin/outward',$v)->assertSessionHasNoErrors();$this->assertEquals($stock,$p->fresh()->stock);$v=$this->payload('confirm');$v['type']='Expired Stock';$this->post('/admin/outward',$v)->assertSessionHasErrors();$v=$this->payload();$v['items'][0]['quantity']=-1;$this->post('/admin/outward',$v)->assertSessionHasErrors('items.0.quantity');}
 public function test_cancelled_order_closes_outward_and_expiry_is_rechecked_at_dispatch(){
 $order=$this->order();$v=$this->payload('confirm');$v['type']='Order Dispatch';$v['order_id']=$order->id;$this->post('/admin/outward',$v)->assertSessionHasNoErrors();$o=Outward::first();$this->action($o,'pack')->assertSessionHasNoErrors();$this->post('/admin/outward/'.$o->id.'/dispatch-details',['partner'=>'Carrier','tracking_number'=>'T1'])->assertSessionHasNoErrors();$p=Product::first();$p->expires_on=today()->subDay()->toDateString();$p->save();DB::table('product_batches')->where('source','Legacy order allocation')->update(['expires_on'=>$p->expires_on]);$this->action($o,'dispatch')->assertSessionHasErrors();$this->assertEquals('Packed',$o->fresh()->status);$this->assertEquals('Placed',$order->fresh()->status);$this->post('/admin/orders/'.$order->id.'/status',['status'=>'Cancelled'])->assertSessionHasNoErrors();$this->assertEquals('Cancelled',$o->fresh()->status);$this->assertNull($o->fresh()->active_order_id);
 }
 public function test_guests_cannot_access_any_outward_endpoint(){auth()->logout();$this->get('/admin/outward')->assertRedirect('/admin/login');$this->get('/admin/outward/create')->assertRedirect('/admin/login');$this->get('/admin/outward/export')->assertRedirect('/admin/login');$this->post('/admin/outward',$this->payload())->assertRedirect('/admin/login');}
 public function test_bulk_packing_rolls_back_invalid_selections(){
 $order=$this->order();$second=$this->order();$v=$this->payload('confirm');$v['type']='Order Dispatch';$v['order_id']=$order->id;$this->post('/admin/outward',$v)->assertSessionHasNoErrors();$o=Outward::first();$this->post('/admin/workspace/bulk-pack',['order_ids'=>[$order->id,$second->id]])->assertSessionHasErrors();$this->assertEquals('Pending',$o->fresh()->status);$this->post('/admin/workspace/bulk-pack',['order_ids'=>[$order->id]])->assertSessionHasNoErrors();$this->assertEquals('Packed',$o->fresh()->status);
 }
}