<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
class CreateStoreTables extends Migration
{
 public function up(){
  Schema::create('password_resets',function(Blueprint $t){$t->string('email')->index();$t->string('token');$t->timestamp('created_at')->nullable();});
  foreach(['roles','permissions','categories','brands','coupons','shipping_methods','banners','settings'] as $table){Schema::create($table,function(Blueprint $t){$t->bigIncrements('id');$t->string('name');$t->boolean('active')->default(true);$t->text('data')->nullable();$t->timestamps();});}
  Schema::table('users',function(Blueprint $t){$t->unsignedBigInteger('role_id')->nullable();$t->boolean('active')->default(true);$t->string('phone')->nullable();});
  Schema::create('role_user',function(Blueprint $t){$t->unsignedBigInteger('role_id');$t->unsignedBigInteger('user_id');$t->unique(['role_id','user_id']);});
  Schema::create('products',function(Blueprint $t){$t->bigIncrements('id');$t->string('name');$t->string('sku')->unique();$t->unsignedBigInteger('category_id')->nullable();$t->unsignedBigInteger('brand_id')->nullable();$t->unsignedInteger('price');$t->unsignedInteger('old_price')->default(0);$t->unsignedInteger('stock')->default(0);$t->string('image')->nullable();$t->text('description')->nullable();$t->text('specifications')->nullable();$t->text('variants')->nullable();$t->text('tags')->nullable();$t->string('badge')->nullable();$t->boolean('featured')->default(false);$t->boolean('active')->default(true);$t->softDeletes();$t->timestamps();$t->index(['active','category_id']);});
  Schema::create('product_images',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('product_id')->index();$t->string('url');$t->unsignedInteger('position')->default(0);});
  Schema::create('carts',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('user_id')->nullable()->index();$t->string('session_key')->unique();$t->timestamps();});
  Schema::create('cart_items',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('cart_id')->index();$t->unsignedBigInteger('product_id');$t->string('variant')->default('Default');$t->unsignedInteger('quantity');$t->unique(['cart_id','product_id','variant']);$t->timestamps();});
  Schema::create('wishlists',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('user_id')->unique();$t->timestamps();});
  Schema::create('wishlist_items',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('wishlist_id');$t->unsignedBigInteger('product_id');$t->unique(['wishlist_id','product_id']);$t->timestamps();});
  Schema::create('addresses',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('user_id')->nullable()->index();$t->string('session_key')->nullable()->index();$t->string('name');$t->string('phone');$t->string('address');$t->string('city');$t->string('state');$t->string('pincode');$t->string('type')->default('Home');$t->boolean('is_default')->default(false);$t->timestamps();});
  Schema::create('orders',function(Blueprint $t){$t->bigIncrements('id');$t->string('number')->unique();$t->string('idempotency_key')->unique();$t->unsignedBigInteger('user_id')->nullable()->index();$t->string('session_key')->index();$t->string('email');$t->string('status')->default('Placed')->index();$t->unsignedInteger('subtotal');$t->unsignedInteger('discount')->default(0);$t->unsignedInteger('shipping')->default(0);$t->unsignedInteger('tax')->default(0);$t->unsignedInteger('total');$t->unsignedBigInteger('coupon_id')->nullable();$t->unsignedBigInteger('shipping_method_id');$t->string('payment_method');$t->boolean('stock_restored')->default(false);$t->text('timeline');$t->timestamps();});
  Schema::create('order_items',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('order_id')->index();$t->unsignedBigInteger('product_id');$t->string('name');$t->string('sku');$t->string('image')->nullable();$t->string('variant');$t->unsignedInteger('quantity');$t->unsignedInteger('price');});
  Schema::create('order_addresses',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('order_id')->unique();$t->text('data');});
  Schema::create('coupon_usages',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('coupon_id')->index();$t->unsignedBigInteger('order_id')->unique();$t->unsignedBigInteger('user_id')->nullable();$t->string('session_key');$t->timestamps();});
  Schema::create('payments',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('order_id')->unique();$t->string('method');$t->string('status')->default('Test — no payment collected');$t->unsignedInteger('amount');$t->timestamps();});
  Schema::create('shipments',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('order_id')->unique();$t->string('method');$t->string('status')->default('Pending');$t->string('tracking_number')->nullable();$t->timestamps();});
  Schema::create('reviews',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('product_id')->index();$t->unsignedBigInteger('user_id');$t->unsignedTinyInteger('rating');$t->string('title');$t->text('text');$t->string('image')->nullable();$t->boolean('approved')->default(false);$t->text('response')->nullable();$t->timestamps();});
  Schema::create('inventory',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('product_id')->index();$t->integer('adjustment');$t->string('reason');$t->unsignedBigInteger('user_id')->nullable();$t->timestamps();});
  foreach(['notifications','support_messages','activity_logs'] as $table){Schema::create($table,function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('user_id')->nullable()->index();$t->string('session_key')->nullable()->index();$t->string('name');$t->text('data');$t->boolean('read')->default(false);$t->timestamps();});}
 }
 public function down(){foreach(['password_resets','activity_logs','support_messages','notifications','inventory','reviews','shipments','payments','coupon_usages','order_addresses','order_items','orders','addresses','wishlist_items','wishlists','cart_items','carts','product_images','products','role_user','settings','banners','shipping_methods','coupons','brands','categories','permissions','roles'] as $table)Schema::dropIfExists($table);Schema::table('users',function(Blueprint $t){$t->dropColumn(['role_id','active','phone']);});}
}
