<?php
namespace App\Http\Controllers;
use App\Product;
use App\Order;
use App\User;
use App\Outward;
use App\StoreRecord;
use Illuminate\Http\Request;
class AdminWorkspaceController extends Controller {
 public function __construct(){$this->middleware(['auth',\App\Http\Middleware\ActiveAccount::class]);}
 public function home(){abort_unless(auth()->user()->canManage('dashboard'),403);$u=auth()->user();$cards=[];
  if($u->canManage('orders')){$cards[]=['label'=>'Orders to prepare','count'=>Order::whereIn('status',['Placed','Confirmed'])->count(),'url'=>'/admin/orders?preset=prepare','hint'=>'Placed and confirmed orders'];$cards[]=['label'=>'In delivery','count'=>Order::whereIn('status',['Shipped','Picked up','On the way'])->count(),'url'=>'/admin/orders?preset=delivery','hint'=>'Shipped and active rider deliveries'];}
  if($u->canManage('inventory')){$cards[]=['label'=>'Awaiting dispatch','count'=>Outward::whereIn('status',['Pending','Packed'])->count(),'url'=>'/admin/outward','hint'=>'Confirmed outward entries'];$cards[]=['label'=>'Low stock','count'=>Product::where('active',true)->where('stock','<=',5)->count(),'url'=>'/admin/products?stock=low','hint'=>'5 units or fewer'];$cards[]=['label'=>'Expiring within 7 days','count'=>\Illuminate\Support\Facades\DB::table('product_batches')->where('remaining_quantity','>',0)->whereBetween('expires_on',[today()->toDateString(),today()->addDays(7)->toDateString()])->count(),'url'=>'/admin/batches?expiry=soon','hint'=>'Inspect batches; FIFO still uses receipt date'];}
  if($u->canManage('support_messages'))$cards[]=['label'=>'Unread support messages','count'=>StoreRecord::in('support_messages')->where('read',false)->count(),'url'=>'/admin/support_messages?unread=1','hint'=>'Customer enquiries'];
  return view('admin.workspace',['cards'=>$cards,'recent'=>$u->canManage('orders')?Order::latest()->limit(8)->get():collect(),'low'=>$u->canManage('inventory')?Product::where('active',true)->where('stock','<=',5)->orderBy('stock')->limit(8)->get():collect()]);
 }
 public function search(Request $r){$r->validate(['q'=>'nullable|string|max:100']);$term=trim($r->input('q',''));$u=$r->user();abort_unless(collect(array_keys(config('store.modules')))->contains(function($m)use($u){return $u->canManage($m);}),403);$results=[];if($term!==''){$like='%'.$term.'%';if($u->canManage('products'))foreach(Product::where(function($q)use($like){$q->where('name','like',$like)->orWhere('sku','like',$like)->orWhereHas('category',function($q)use($like){$q->where('name','like',$like);});})->limit(10)->get() as $p)$results[]=['kind'=>'Product','title'=>$p->name,'detail'=>$p->sku.' · '.$p->stock.' in stock','url'=>route('admin.edit',['products',$p->id])];if($u->canManage('orders'))foreach(Order::where(function($q)use($like){$q->where('number','like',$like)->orWhere('invoice_number','like',$like)->orWhere('email','like',$like);})->limit(10)->get() as $o)$results[]=['kind'=>'Order','title'=>$o->number,'detail'=>$o->email.' · '.$o->status,'url'=>route('orders.show',$o)];if($u->canManage('users'))foreach(User::where(function($q)use($like){$q->where('name','like',$like)->orWhere('email','like',$like)->orWhere('phone','like',$like);})->limit(10)->get() as $c)$results[]=['kind'=>'Account','title'=>$c->name,'detail'=>$c->email,'url'=>route('admin.edit',['users',$c->id])];if($u->canManage('inventory'))foreach(Outward::where('number','like',$like)->orWhere('tracking_number','like',$like)->limit(10)->get() as $o)$results[]=['kind'=>'Outward','title'=>$o->number,'detail'=>$o->type.' · '.$o->status,'url'=>route('admin.outward.show',$o)];if($u->canManage('inventory'))foreach(\Illuminate\Support\Facades\DB::table('product_batches')->join('products','products.id','=','product_batches.product_id')->where(function($q)use($like){$q->where('batch_number','like',$like)->orWhere('supplier_invoice_no','like',$like);})->select('product_batches.*','products.name')->limit(10)->get() as $b)$results[]=['kind'=>'Stock batch','title'=>$b->batch_number,'detail'=>$b->name.' · '.($b->supplier_invoice_no?:'Opening stock'),'url'=>route('admin.batches',['q'=>$term])];}return view('admin.search',['results'=>$results,'term'=>$term]);}
 public function bulkPack(Request $r){abort_unless($r->user()->canManage('orders')&&$r->user()->canManage('inventory'),403);$v=$r->validate(['order_ids'=>'required|array|min:1|max:20','order_ids.*'=>'required|integer|distinct|exists:orders,id']);\Illuminate\Support\Facades\DB::transaction(function()use($v){foreach(collect($v['order_ids'])->sort()->values() as $id){$o=Outward::where('active_order_id',$id)->first();if(!$o||$o->status!=='Pending')\App\Services\Commerce::error('Every selected order must have a confirmed pending outward entry.');\App\Services\OutwardFlow::transition($o,'pack');}},3);return back()->with('success','Selected orders marked packed.');}
}