<?php
namespace App\Http\Controllers;
use App\Order;
use App\User;
use App\StoreRecord;
use App\Services\Commerce;
use App\Services\Delivery;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class DeliveryController extends Controller {
 public function location(Request $r){$v=$r->validate(['pincode'=>'required|regex:/^[1-9][0-9]{5}$/']);session(['delivery_pincode'=>$v['pincode']]);return back()->with('notice',Delivery::zone($v['pincode'])?'Delivery area selected. Check available times at checkout.':'Delivery is not yet available here. You can still browse.');}
 public function suggestions(Request $r){$r->validate(['q'=>'nullable|string|max:100']);$q=\App\Product::where('active',true);\App\Services\Catalog::search($q,$r->input('q',''));return response()->json($q->limit(8)->get(['id','name','image','price']));}
 public function slots(Request $r){$r->validate(['address_id'=>'required|integer']);$a=Commerce::owned(\App\Address::query())->findOrFail($r->address_id);return response()->json(['options'=>Delivery::options(Commerce::items(),$a->pincode),'required'=>Delivery::requiresSchedule(Commerce::items()),'message'=>Delivery::zone($a->pincode)?'No compatible delivery time? Separate fresh and standard products or try another address.':'This pincode is outside the delivery area.']);}
 private function rider(){abort_unless(auth()->check()&&auth()->user()->active&&optional(StoreRecord::in('roles')->find(auth()->user()->role_id))->name==='delivery partner',403);}
 public function riderPanel(){$this->rider();$deliveries=DB::table('deliveries')->where('rider_id',auth()->id())->orderByDesc('id')->get()->map(function($d){$d->order=Order::find($d->order_id);return $d;});return view('delivery.rider',compact('deliveries'));}
 public function update(Request $r,Order $order){$this->rider();return DB::transaction(function()use($r,$order){$o=Order::where('id',$order->id)->lockForUpdate()->firstOrFail();$d=DB::table('deliveries')->where('order_id',$o->id)->lockForUpdate()->first();abort_unless($d&&(int)$d->rider_id===auth()->id(),403);abort_if(in_array($o->status,['Cancelled','Refunded','Delivered'],true),409);$v=$r->validate(['latitude'=>'nullable|required_with:longitude|numeric|between:-90,90','longitude'=>'nullable|required_with:latitude|numeric|between:-180,180','status'=>'nullable|in:Picked up,On the way,Delivered','eta_minutes'=>'nullable|integer|between:1,240']);if(isset($v['latitude']))DB::table('deliveries')->where('id',$d->id)->update(['latitude'=>$v['latitude'],'longitude'=>$v['longitude'],'location_at'=>now(),'updated_at'=>now()]);if(isset($v['eta_minutes']))DB::table('deliveries')->where('id',$d->id)->update(['eta_at'=>now()->addMinutes($v['eta_minutes']),'updated_at'=>now()]);if(!empty($v['status'])){$next=['Placed'=>'Picked up','Confirmed'=>'Picked up','Packing'=>'Picked up','Packed'=>'Picked up','Shipped'=>'Picked up','Picked up'=>'On the way','On the way'=>'Delivered'];if(($next[$o->status]??null)!==$v['status'])Commerce::error('Follow pickup → on the way → delivered.');Commerce::status($o,$v['status'],true);}return $r->expectsJson()?response()->json(['saved'=>true]):back()->with('success','Delivery updated.');});}
 public function tracking(Order $order){abort_unless(auth()->check()&&((int)auth()->id()===(int)$order->user_id||auth()->user()->canManage('orders')),403);$d=DB::table('deliveries')->where('order_id',$order->id)->first();$active=!in_array($order->status,['Delivered','Cancelled','Refunded'],true);return response()->json(['status'=>$order->status,'timeline'=>$order->timeline,'delivery'=>$d?['from'=>$d->promised_from,'to'=>$d->promised_to,'eta'=>$active?$d->eta_at:null,'latitude'=>$active?$d->latitude:null,'longitude'=>$active?$d->longitude:null,'updated'=>$active?$d->location_at:null,'rider'=>$d->rider_id?optional(User::find($d->rider_id))->name:null]:null]);}
 public function admin(){abort_unless(auth()->user()->canManage('orders'),403);return view('delivery.admin',['zones'=>DB::table('delivery_zones')->get(),'slots'=>DB::table('delivery_slots')->where('ends_at','>',now())->orderBy('starts_at')->get(),'deliveries'=>DB::table('deliveries')->orderByDesc('id')->limit(50)->get(),'riders'=>User::where('active',true)->whereIn('role_id',StoreRecord::in('roles')->where('name','delivery partner')->pluck('id'))->get()]);}
 public function zoneSave(Request $r){abort_unless(auth()->user()->canManage('orders'),403);$v=$r->validate(['name'=>'required|string|max:100','pincodes'=>'required|regex:/^[1-9][0-9]{5}(?:\s*,\s*[1-9][0-9]{5})*$/','opens_at'=>'required|date_format:H:i','closes_at'=>'required|date_format:H:i|after:opens_at','travel_minutes'=>'required|integer|between:1,240']);$v['express']=$r->boolean('express');$v['active']=$r->boolean('active');$v['updated_at']=now();if($r->filled('id')){DB::table('delivery_zones')->where('id',$r->validate(['id'=>'required|exists:delivery_zones,id'])['id'])->update($v);}else DB::table('delivery_zones')->insert($v+['created_at'=>now()]);return back()->with('success','Service area saved.');}
 public function slotSave(Request $r){abort_unless(auth()->user()->canManage('orders'),403);$v=$r->validate(['zone_id'=>'required|exists:delivery_zones,id','starts_at'=>'required|date|after:now','ends_at'=>'required|date|after:starts_at','capacity'=>'required|integer|between:1,1000']);$zone=DB::table('delivery_zones')->find($v['zone_id']);$start=\Carbon\Carbon::parse($v['starts_at']);$end=\Carbon\Carbon::parse($v['ends_at']);if(!$start->isSameDay($end)||$start->format('H:i:s')<$zone->opens_at||$end->format('H:i:s')>$zone->closes_at)Commerce::error('Slots must stay within the service area opening hours.');$v['starts_at']=$start;$v['ends_at']=$end;DB::table('delivery_slots')->insert($v+['created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Delivery slot created.');}
 public function assign(Request $r,Order $order){abort_unless(auth()->user()->canManage('orders'),403);$v=$r->validate(['rider_id'=>'required|exists:users,id']);DB::transaction(function()use($v,$order){$u=User::where('id',$v['rider_id'])->lockForUpdate()->firstOrFail();abort_unless($u->active&&optional(StoreRecord::in('roles')->find($u->role_id))->name==='delivery partner',422);$o=Order::where('id',$order->id)->lockForUpdate()->firstOrFail();if(in_array($o->status,['Cancelled','Delivered','Refunded'],true))Commerce::error('This delivery is closed.');if(DB::table('deliveries')->join('orders','orders.id','=','deliveries.order_id')->where('rider_id',$u->id)->where('order_id','!=',$o->id)->whereNotIn('orders.status',['Delivered','Cancelled','Refunded'])->exists())Commerce::error('This rider already has an active delivery.');$count=DB::table('deliveries')->where('order_id',$o->id)->update(['rider_id'=>$u->id,'latitude'=>null,'longitude'=>null,'location_at'=>null,'eta_at'=>null,'updated_at'=>now()]);if(!$count)Commerce::error('This older order has no delivery schedule.');Commerce::notify($o,'Delivery partner assigned: '.$u->name);});return back()->with('success','Rider assigned.');}
}
