<?php
namespace App\Http\Controllers;
use App\Outward;
use App\Order;
use App\Product;
use App\User;
use App\StoreRecord;
use App\Services\Commerce;
use App\Services\OutwardFlow;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
class OutwardController extends Controller {
 const TYPES=['Order Dispatch','Manual Stock Issue','Damaged Stock','Expired Stock','Internal Transfer','Other'];
 const STATUSES=['Draft','Pending','Packed','Dispatched','Delivered','Completed','Cancelled','Returned'];
 public function __construct(){$this->middleware(['auth',\App\Http\Middleware\ActiveAccount::class]);$this->middleware(function($r,$next){abort_unless($r->user()->canManage('inventory'),403);return $next($r);});}
 private function query(Request $r){$v=$r->validate(['q'=>'nullable|string|max:100','type'=>['nullable',Rule::in(self::TYPES)],'status'=>['nullable',Rule::in(self::STATUSES)],'from'=>'nullable|date','to'=>'nullable|date|after_or_equal:from']);$q=Outward::with(['order','items','creator']);if(!empty($v['q'])){$term='%'.$v['q'].'%';$q->where(function($q)use($term){$q->where('number','like',$term)->orWhere('tracking_number','like',$term)->orWhereHas('order',function($q)use($term){$q->where('number','like',$term)->orWhere('email','like',$term);})->orWhereHas('items',function($q)use($term){$q->where('sku','like',$term)->orWhere('name','like',$term);});});}foreach(['type','status'] as $f)if(!empty($v[$f]))$q->where($f,$v[$f]);if(!empty($v['from']))$q->whereDate('outward_date','>=',$v['from']);if(!empty($v['to']))$q->whereDate('outward_date','<=',$v['to']);return $q;}
 public function index(Request $r){return view('admin.outward.index',['rows'=>$this->query($r)->latest()->paginate(15)->appends($r->query()),'types'=>self::TYPES,'statuses'=>self::STATUSES,'counts'=>Outward::select('status',DB::raw('count(*) as record_count'))->groupBy('status')->pluck('record_count','status')]);}
 private function formData($entry=null){return ['entry'=>$entry,'types'=>self::TYPES,'products'=>Product::orderBy('name')->get(),'orders'=>Order::with('items')->whereIn('status',['Placed','Confirmed','Packing','Packed'])->where('stock_restored',false)->where(function($q)use($entry){$q->whereNotIn('id',Outward::whereNotNull('active_order_id')->pluck('active_order_id'));if($entry&&$entry->order_id)$q->orWhere('id',$entry->order_id);})->latest()->get(),'requestKey'=>$entry?$entry->request_key:(string)Str::uuid()];}
 public function create(){return view('admin.outward.create',$this->formData());}
 public function edit(Outward $outward){abort_unless($outward->status==='Draft',409,'Only drafts can be edited.');$outward->load('items');return view('admin.outward.create',$this->formData($outward));}
 public function store(Request $r){return $this->save($r);}
 public function update(Request $r,Outward $outward){return $this->save($r,$outward);}
 private function save(Request $r,$entry=null){
  $v=$r->validate(['request_key'=>'required|uuid','type'=>['required',Rule::in(self::TYPES)],'outward_date'=>'required|date|before_or_equal:today','source'=>'required|string|max:100','destination'=>'nullable|required_if:type,Internal Transfer|string|max:100|different:source','reason'=>'nullable|required_unless:type,Order Dispatch|string|max:1000','order_id'=>'nullable|required_if:type,Order Dispatch|exists:orders,id','notes'=>'nullable|string|max:2000','intent'=>'required|in:draft,confirm','items'=>'nullable|array|max:100','items.*.product_id'=>'required|integer|distinct|exists:products,id','items.*.quantity'=>'required|integer|between:1,1000000']);
  $o=DB::transaction(function()use($v,$entry){
   if(!$entry){$existing=Outward::where('request_key',$v['request_key'])->first();if($existing)return $existing;}else{$entry=Outward::where('id',$entry->id)->lockForUpdate()->firstOrFail();if($entry->status!=='Draft')Commerce::error('Only drafts can be edited.');}
   $order=null;$lines=[];
   if($v['type']==='Order Dispatch'){$order=Order::where('id',$v['order_id'])->lockForUpdate()->firstOrFail();if(!in_array($order->status,['Placed','Confirmed','Packing','Packed'],true)||$order->stock_restored)Commerce::error('Choose an order that is awaiting dispatch.');if(Outward::where('active_order_id',$order->id)->when($entry,function($q)use($entry){$q->where('id','!=',$entry->id);})->exists())Commerce::error('This order already has an outward entry.');foreach($order->items as $i)$lines[]=['product_id'=>$i->product_id,'order_item_id'=>$i->id,'name'=>$i->name,'sku'=>$i->sku,'variant'=>$i->variant,'quantity'=>$i->quantity,'unit_value'=>$i->price,'expires_on'=>optional(Product::withTrashed()->find($i->product_id))->expires_on];}
   else{if(empty($v['items']))Commerce::error('Add at least one product.');foreach($v['items'] as $i){$p=Product::findOrFail($i['product_id']);$lines[]=['product_id'=>$p->id,'name'=>$p->name,'sku'=>$p->sku,'quantity'=>$i['quantity'],'unit_value'=>$p->price,'expires_on'=>$p->expires_on];}}
   $o=$entry?:new Outward(['number'=>'OUT-'.strtoupper(Str::random(10)),'request_key'=>$v['request_key'],'created_by'=>auth()->id(),'timeline'=>[]]);
   $o->fill(['type'=>$v['type'],'outward_date'=>$v['outward_date'],'source'=>$v['source'],'destination'=>$v['type']==='Internal Transfer'?$v['destination']:null,'reason'=>$v['reason']??null,'notes'=>$v['notes']??null,'order_id'=>$order?$order->id:null,'active_order_id'=>$order?$order->id:null]);$o->save();$o->items()->delete();$o->items()->createMany($lines);OutwardFlow::event($o,'Draft',$entry?'Draft updated':'Draft created');if($v['intent']==='confirm')OutwardFlow::transition($o,'confirm');return $o;
  },3);return redirect()->route('admin.outward.show',$o)->with('success','Outward saved.');
 }
 public function show(Outward $outward){$outward->load(['items','order','creator']);$shipment=$outward->order_id?DB::table('shipments')->where('order_id',$outward->order_id)->first():null;$delivery=$outward->order_id?DB::table('deliveries')->where('order_id',$outward->order_id)->first():null;return view('admin.outward.show',['entry'=>$outward,'shipment'=>$shipment,'delivery'=>$delivery,'riders'=>User::where('active',true)->whereIn('role_id',StoreRecord::in('roles')->where('name','delivery partner')->pluck('id'))->get()]);}
 public function action(Request $r,Outward $outward){$v=$r->validate(['action'=>'required|in:confirm,pack,dispatch,deliver,cancel,return']);if(in_array($v['action'],['pack','dispatch','deliver','return'],true))abort_unless($r->user()->canManage('orders'),403);if($v['action']==='return')$v+=$r->validate(['return_condition'=>'required|in:restock,loss','return_reason'=>'required|string|max:1000']);OutwardFlow::transition($outward,$v['action'],$v);return back()->with('success','Outward updated.');}
 public function dispatchDetails(Request $r,Outward $outward){abort_unless($r->user()->canManage('orders'),403);$v=$r->validate(['partner'=>'required|string|max:100','tracking_number'=>'nullable|string|max:100','rider_id'=>'nullable|integer|exists:users,id','expected_at'=>'nullable|date|after:now']);DB::transaction(function()use($v,$outward){$o=Outward::where('id',$outward->id)->lockForUpdate()->firstOrFail();if($o->type!=='Order Dispatch'||!in_array($o->status,['Draft','Pending','Packed'],true))Commerce::error('Dispatch details can only be edited before dispatch.');if(!empty($v['rider_id'])){$u=User::findOrFail($v['rider_id']);if(!$u->active||optional(StoreRecord::in('roles')->find($u->role_id))->name!=='delivery partner')Commerce::error('Select an active delivery partner.');}$v['expected_at']=empty($v['expected_at'])?null:\Carbon\Carbon::parse($v['expected_at'])->toDateTimeString();$o->fill($v);$o->save();OutwardFlow::event($o,$o->status,'Dispatch details updated');});return back()->with('success','Dispatch details saved.');}
 public function printSlip(Outward $outward){$outward->load(['items','order']);return view('admin.outward.print',['entry'=>$outward]);}
 public function export(Request $r){$rows=$this->query($r)->latest()->get();return response()->streamDownload(function()use($rows){$f=fopen('php://output','w');fputcsv($f,['Outward','Date','Type','Status','Order','SKU','Product','Quantity','Unit value INR','Tracking']);foreach($rows as $o)foreach($o->items as $i){$row=[$o->number,$o->outward_date,$o->type,$o->status,optional($o->order)->number,$i->sku,$i->name,$i->quantity,$i->unit_value/100,$o->tracking_number];fputcsv($f,array_map(function($v){return is_string($v)&&preg_match('/^[=+@\-]/',$v)?"'".$v:$v;},$row));}fclose($f);},'novacart-outwards.csv',['Content-Type'=>'text/csv']);}
}
