@extends('layouts.admin')
@section('admin_title','Stock Outward')
@section('admin_content')
<link rel="stylesheet" href="{{ asset('outward.css') }}">
<div class="ow">
 <div class="ow-head"><div><h2>Stock outward</h2><p>Manage dispatches, stock issues and inventory losses.</p></div><div><a class="ow-btn" href="{{ route('admin.outward.export',request()->query()) }}">Export CSV</a> <a class="ow-btn ow-primary" href="{{ route('admin.outward.create') }}">＋ New outward</a></div></div>
 @include('admin.outward.errors')
 <div class="ow-stats"><div class="ow-stat">Drafts<strong>{{ $counts['Draft']??0 }}</strong></div><div class="ow-stat">Awaiting dispatch<strong>{{ ($counts['Pending']??0)+($counts['Packed']??0) }}</strong></div><div class="ow-stat">Dispatched<strong>{{ $counts['Dispatched']??0 }}</strong></div><div class="ow-stat">Completed / delivered<strong>{{ ($counts['Completed']??0)+($counts['Delivered']??0) }}</strong></div></div>
 <div class="ow-card"><form class="ow-filters" method="get" action="{{ route('admin.outward') }}"><div><label for="q">Search outward, order, email or SKU</label><input id="q" name="q" value="{{ request('q') }}" placeholder="Search records…" maxlength="100"></div><div><label for="type">Type</label><select id="type" name="type"><option value="">All types</option>@foreach($types as $t)<option {{ request('type')===$t?'selected':'' }}>{{ $t }}</option>@endforeach</select></div><div><label for="status">Status</label><select id="status" name="status"><option value="">All statuses</option>@foreach($statuses as $s)<option {{ request('status')===$s?'selected':'' }}>{{ $s }}</option>@endforeach</select></div><div><label for="from">From</label><input type="date" id="from" name="from" value="{{ request('from') }}"></div><div><label for="to">To</label><input type="date" id="to" name="to" value="{{ request('to') }}"></div><div><button class="ow-btn ow-primary">Filter</button><a href="{{ route('admin.outward') }}">Reset</a></div></form></div>
 <div class="ow-card"><div class="ow-table-wrap"><table><thead><tr><th>Outward</th><th>Type / source</th><th>Order</th><th>Quantity</th><th>Goods value</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($rows as $o)<tr><td><a href="{{ route('admin.outward.show',$o) }}"><strong>{{ $o->number }}</strong></a><small>{{ $o->outward_date }}</small></td><td>{{ $o->type }}<small>{{ $o->source }}</small></td><td>@if($o->order)<a href="{{ route('orders.show',$o->order_id) }}">{{ $o->order->number }}</a><small>{{ $o->order->email }}</small>@else — @endif</td><td>{{ $o->items->sum('quantity') }}<small>{{ $o->items->count() }} lines</small></td><td>{{ \App\Services\Commerce::money($o->total) }}</td><td><span class="ow-badge {{ $o->status }}">{{ $o->status }}</span></td><td><a href="{{ route('admin.outward.show',$o) }}">View</a>@if($o->status==='Draft') · <a href="{{ route('admin.outward.edit',$o) }}">Edit</a>@endif</td></tr>@empty<tr><td colspan="7" class="ow-empty">No outward records found. Create an outward to get started.</td></tr>@endforelse</tbody></table></div>{{ $rows->links() }}</div>
 <div class="ow-note">Order stock is deducted at checkout. Dispatch records do not deduct it again. Manual stock issues are applied when confirmed.</div>
</div>
@endsection
