@extends('layouts.admin')
@section('admin_title','Outward Details')
@section('admin_content')
<link rel="stylesheet" href="{{ asset('outward.css') }}">
<div class="ow"><div class="ow-head"><div><h2>{{ $entry->number }}</h2><span class="ow-badge {{ $entry->status }}">{{ $entry->status }}</span> · {{ $entry->type }}</div><div><a class="ow-btn" href="{{ route('admin.outward') }}">All outward</a> <a class="ow-btn" href="{{ route('admin.outward.print',$entry) }}" target="_blank" rel="noopener">Print dispatch note</a>@if($entry->status==='Draft') <a class="ow-btn" href="{{ route('admin.outward.edit',$entry) }}">Edit draft</a>@endif</div></div>
@include('admin.outward.errors')
<div class="ow-grid"><div class="ow-card"><h3>Movement information</h3><p>Date: {{ $entry->outward_date }}<br>Source: {{ $entry->source }}@if($entry->destination)<br>Destination: {{ $entry->destination }}@endif<br>Created by: {{ optional($entry->creator)->name }}<br>Confirmed: {{ $entry->confirmed_at?:'Not yet confirmed' }}</p>@if($entry->reason)<strong>Reason</strong><p>{{ $entry->reason }}</p>@endif @if($entry->notes)<strong>Notes</strong><p>{{ $entry->notes }}</p>@endif</div><div class="ow-card"><h3>Order and delivery</h3>@if($entry->order)<a href="{{ route('orders.show',$entry->order_id) }}">{{ $entry->order->number }} · {{ $entry->order->status }}</a><p>{{ $entry->order->email }}</p>@php($address=$entry->order->address)<p>{{ $address['name']??'' }} · {{ $address['phone']??'' }}<br>{{ $address['address']??'' }}, {{ $address['city']??'' }} {{ $address['pincode']??'' }}</p><p>Carrier: {{ $entry->partner?:'Not assigned' }}<br>Tracking: {{ $entry->tracking_number?:'Not supplied' }}<br>Expected: {{ $entry->expected_at?:($delivery?$delivery->promised_to:'Not scheduled') }}</p><a href="{{ url('/admin/delivery') }}">Delivery operations</a>@else<p>This movement is independent of a customer order.</p>@endif</div></div>
<div class="ow-card"><h3>Products</h3>@include('admin.batch-allocation',['entry'=>$entry])<div class="ow-table-wrap"><table><thead><tr><th>Product</th><th>SKU / variant</th><th>Expiry</th><th>Quantity</th><th>Unit value</th><th>Line value</th></tr></thead><tbody>@foreach($entry->items as $i)<tr><td>{{ $i->name }}</td><td>{{ $i->sku }}<small>{{ $i->variant }}</small></td><td>{{ $i->expires_on?:'—' }}</td><td>{{ $i->quantity }}</td><td>{{ \App\Services\Commerce::money($i->unit_value) }}</td><td>{{ \App\Services\Commerce::money($i->quantity*$i->unit_value) }}</td></tr>@endforeach</tbody></table></div><div class="ow-summary"><span>{{ $entry->items->sum('quantity') }} units</span><span>{{ \App\Services\Commerce::money($entry->total) }}</span></div><p>Goods value only. Customer payment, tax and shipping remain on the original order.</p></div>
@if($entry->type==='Order Dispatch' && in_array($entry->status,['Draft','Pending','Packed'],true) && auth()->user()->canManage('orders'))
<div class="ow-card"><h3>Dispatch details</h3><form method="post" action="{{ route('admin.outward.dispatch-details',$entry) }}">@csrf<div class="ow-grid"><div><label for="partner">Carrier / delivery service</label><input id="partner" name="partner" value="{{ old('partner',$entry->partner) }}" maxlength="100" placeholder="Self delivery or courier name" required></div><div><label for="tracking">Tracking number</label><input id="tracking" name="tracking_number" value="{{ old('tracking_number',$entry->tracking_number) }}" maxlength="100"></div><div><label for="rider">Delivery partner (optional)</label><select id="rider" name="rider_id"><option value="">Use carrier tracking</option>@foreach($riders as $r)<option value="{{ $r->id }}" {{ (string)old('rider_id',$entry->rider_id)===(string)$r->id?'selected':'' }}>{{ $r->name }}</option>@endforeach</select></div><div><label for="expected">Expected delivery (optional)</label><input id="expected" type="datetime-local" name="expected_at" value="{{ old('expected_at',$entry->expected_at?\Carbon\Carbon::parse($entry->expected_at)->format('Y-m-d\TH:i'):'') }}"></div></div><p>Assign a rider only for an order with an existing delivery schedule. Otherwise provide carrier tracking.</p><button class="ow-btn">Save dispatch details</button></form></div>@endif
<div class="ow-card"><h3>Next action</h3><div class="ow-actions">
@foreach(['Draft'=>['confirm'=>'Confirm outward'],'Pending'=>['pack'=>'Mark packed'],'Packed'=>['dispatch'=>'Dispatch order'],'Dispatched'=>['deliver'=>'Mark delivered']] as $state=>$actions)
@if($entry->status===$state) @foreach($actions as $action=>$label) @if($action==='confirm'||auth()->user()->canManage('orders'))<form method="post" action="{{ route('admin.outward.action',$entry) }}">@csrf<input type="hidden" name="action" value="{{ $action }}"><button class="ow-btn ow-primary">{{ $label }}</button></form>@endif @endforeach @endif @endforeach
@if(in_array($entry->status,['Draft','Pending','Packed'],true))<form method="post" action="{{ route('admin.outward.action',$entry) }}">@csrf<input type="hidden" name="action" value="cancel"><button class="ow-btn ow-danger">Cancel outward entry</button></form>@endif
@if(in_array($entry->status,['Completed','Delivered','Cancelled','Returned'],true))<p>This entry is closed. Its audit history is preserved.</p>@endif
</div><p>Cancelling an outward entry does not cancel the customer's order. Confirmed manual stock movements cannot be edited or deleted.</p></div>
@if($entry->status==='Delivered' && auth()->user()->canManage('orders'))<div class="ow-card"><h3>Receive returned goods</h3><p>For partial returns or an existing customer request, use <a href="{{ route('admin.returns') }}">Returns &amp; refunds</a>. The form below records a new full return only when no items have already been requested. Inspect goods before recording them. This does not issue a payment refund.</p><form method="post" action="{{ route('admin.outward.action',$entry) }}">@csrf<input type="hidden" name="action" value="return"><label for="condition">Inspection result</label><select id="condition" name="return_condition" required><option value="">Choose result</option><option value="restock">All items are usable — restore stock</option><option value="loss">Damaged or unusable — do not restore stock</option></select><label for="return-reason">Return and inspection notes</label><textarea id="return-reason" name="return_reason" required maxlength="1000"></textarea><button class="ow-btn">Record received return</button></form></div>@endif
<div class="ow-card"><h3>Activity history</h3><ol class="ow-timeline">@foreach(array_reverse($entry->timeline?:[]) as $event)<li><strong>{{ $event['status'] }}</strong><small>{{ $event['at'] }} · {{ $event['by'] }}</small>{{ $event['note'] }}</li>@endforeach</ol></div>
</div>
@endsection
